### ISSUE TITLE
Chat message time Issue

### ISSUE THREAD

**Issue by krishna9960** [TheCreatives/dlinx.meteor.com#17]
When ever user send a message the time below that message doesn't get updated..

Its always "in a few seconds"

**Comment by krishna9960** [comment]
Another observation regarding timing.
When we refresh the browser tab or Re-Login the chat app and see the chat history, It will show the updated time but not updating dynamically .

**Comment by mayankkwl** [comment]
Not able to reproduce it, Krishna please provide the correct steps ;)

**Comment by dlinx** [comment]
Fixed..
